########################################
##      Tax Computation System        ##
########################################
# Docker system composition descriptor #
########################################
# Author: Sebastien Mosser             #
# Version: 1.0                         #
########################################

## Start the system with "docker-compose up -d"
## Shutdown it with "docker-compose down"
## To clean your docker install: "docker system prune"
## To purge your docker install: "docker system prune -a"

version: '3'

services:

  tax-computation:                # Tax Computation, on port 9090
    container_name: tcs-computation
    image: petitroll/tcs-rpc
    ports:
      - "9090:8080"

  id-generator:                   # ID generators, on port 9070
    container_name: tcs-generator
    image: petitroll/tcs-rest
    ports:
      - "9070:8080"

  citizen-registry:               # Citizen registry, on port 9080
    container_name: tcs-citizens
    image: petitroll/tcs-doc
    environment:
      - db_host=tcs-database
      - db_port=27017
    depends_on:
      - database
    ports:
      - "9080:8080"

  database:                       # MongoDB database, on port 27017
    container_name: tcs-database
    image: mongo:3.0
    volumes:
      - "./mongo_data:/data/db"
    ports:
      - "27017:27017"

  integration-bus:  # To attach to this container at runtime: docker exec -it tcs-bus sh
    container_name: tcs-bus
#    image: petitroll/tcs-bus
    image: petitroll/esb  # DEBUG
    volumes:
      - "./service_mix_deploy:/servicemix/deploy" # DEBUG
      - "./camel_input:/servicemix/camel/input"
      - "./camel_output:/servicemix/camel/output"
    ports:
      - "8181:8181"
    depends_on:
      - tax-computation
      - id-generator
      - citizen-registry

  cadvisor:                       # Container monitoring, on port 8090
    container_name: tcs-monitoring
    image: petitroll/cadvisor     # filesystem error in the official image ... fixed in 'monitoring'
    ports:
      - "8090:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
